import React, { createContext, useContext, useState } from 'react';

// Données des langues disponibles
export const languages = [
  {
    code: "FR",
    name: "Français",
    flag: "https://flagcdn.com/16x12/fr.png"
  },
  {
    code: "EN",
    name: "English",
    flag: "https://flagcdn.com/16x12/gb.png"
  },
  {
    code: "ES",
    name: "Español",
    flag: "https://flagcdn.com/16x12/es.png"
  },
  {
    code: "DE",
    name: "Deutsch",
    flag: "https://flagcdn.com/16x12/de.png"
  }
];

// Traductions
const translations = {
  FR: {
    // Header
    "deliverTo": "Livrer à",
    "searchIn": "Rechercher dans",
    "hello": "Bonjour, identifiez-vous",
    "accountLists": "Compte & Listes",
    "signIn": "Se connecter / Créer un compte",
    "orders": "Vos commandes",
    "favourites": "Vos favoris",
    "returns": "Vos retours",
    "addresses": "Vos adresses",
    "payment": "Vos moyens de paiement",
    "lists": "Vos listes",
    "logout": "Déconnexion",
    "returnsShort": "Retours",
    "andOrders": "et Commandes",
    "cart": "Panier",
    "all": "Toutes",
    "dailyDeals": "Offres du jour",
    "customerService": "Service Client",
    "giftCards": "Cartes cadeaux",
    "sell": "Vendre",
    "close": "Fermer le menu",
    "deliver_to": "Livrer à",
    "hello_identify": "Bonjour, identifiez-vous",
    "account_lists": "Compte & Listes",
    "login": "Se connecter",
    "create_account": "Créer un compte",
    "and_orders": "et Commandes",
    "search_placeholder": "Rechercher dans",
    "shoes": "Chaussures",
    "clothing": "Vêtements",
    "accessories": "Accessoires",
    "promotions": "Promotions",
    "new": "Nouveautés",
    "deals": "Offres du jour",
    "gift_cards": "Cartes Cadeaux",
    "pants": "Pantalons",
    "jackets_coats": "Vestes & Manteaux",
    "bags": "Sacs",
    "belts": "Ceintures",
    "glasses": "Lunettes",
    "ongoing_offers": "Offres en cours",
    "recent_products": "Produits récents",
    // Catégories
    "chaussures": "Chaussures",
    "pantalons": "Pantalons",
    "vestes": "Vestes",
    "accessoires": "Accessoires",
    "Homme": "Homme",
    "Femme": "Femme",
    "Enfant": "Enfant",
    "Bébé": "Bébé",
    "Ceintures": "Ceintures",
    "Sacs": "Sacs",
    "Lunettes": "Lunettes",
    "Casquettes": "Casquettes",
    "Offres en cours": "Offres en cours",
    "Nouveautés": "Nouveautés",
    "Produits récents": "Produits récents",
    "Meilleures ventes": "Meilleures ventes",
    
    // MainContent
    "kitchen_essentials": "Kitchen essentials",
    "under_50": "Under $50",
    "sneakers_collection": "Sneakers Collection",
    "spring_new_2025": "Nouveautés printemps 2025",
    "special_offers": "Offres Spéciales",
    "up_to_40_off": "Jusqu'à -40% sur une sélection",
    "trendy_shoes_for_all": "Chaussures tendance pour tous",
    "stylish_pants_for_every_occasion": "Pantalons stylés pour chaque occasion",
    "elegant_jackets_for_all_seasons": "Vestes élégantes pour toutes saisons",
    "accessories_that_complete_your_style": "Accessoires qui complètent votre style",
    "current_offers_and_new": "Offres du moment et Nouveautés",
    "man": "Homme",
    "woman": "Femme",
    "child": "Enfant",
    "baby": "Bébé",
    "see_all_offers": "Voir toutes les offres",
    "nike_air_max_270": "Nike Air Max 270",
    "adidas_ultraboost_22": "Adidas Ultraboost 22",
    "puma_rs_x": "Puma RS-X",
    "new_balance_574": "New Balance 574",
    "levis_501_jeans": "Levi's 501 Jeans",
    "calvin_klein_chinos": "Calvin Klein Chinos",
    "tommy_hilfiger_cargo": "Tommy Hilfiger Cargo",
    "gap_slim_fit": "Gap Slim Fit",
    "north_face_jacket": "The North Face Jacket",
    "columbia_omni_heat": "Columbia Omni-Heat",
    "patagonia_down_jacket": "Patagonia Down Jacket",
    "canada_goose_parka": "Canada Goose Parka",
    "louis_vuitton_bag": "Louis Vuitton Bag",
    "gucci_belt": "Gucci Belt",
    "ray_ban_sunglasses": "Ray-Ban Sunglasses",
    "rolex_watch": "Rolex Watch",
    "nike_air_jordan": "Nike Air Jordan",
    "adidas_yeezy": "Adidas Yeezy",
    "supreme_hoodie": "Supreme Hoodie",
    "off_white_sneakers": "Off-White Sneakers",
    
    // Pages catégories
    "welcome_to_man_page": "Bienvenue sur la page Homme",
    "welcome_to_woman_page": "Bienvenue sur la page Femme",
    "welcome_to_child_page": "Bienvenue sur la page Enfant",
    "welcome_to_baby_page": "Bienvenue sur la page Bébé",
    "man_category_page": "Page catégorie Homme",
    "woman_category_page": "Page catégorie Femme",
    "child_category_page": "Page catégorie Enfant",
    "baby_category_page": "Page catégorie Bébé",
    
    // Page catégorie Homme
    "filters": "Filtres",
    "brands": "Marches",
    "price": "Prix",
    "all_prices": "Tous les prix",
    "under": "Moins de",
    "over": "Plus de",
    "availability": "Disponibilité",
    "in_stock": "En stock",
    "prime": "Prime",
    "results_for": "résultats pour",
    "man_shoes": "chaussures homme",
    "sort_by": "Trier par",
    "featured": "Recommandés",
    "price_low_to_high": "Prix croissant",
    "price_high_to_low": "Prix décroissant",
    "customer_reviews": "Avis clients",
    "newest_arrivals": "Nouveautés",
    "fast_delivery": "Livraison rapide",
    "out_of_stock": "Rupture de stock",
    "add_to_cart": "Ajouter au panier",
    "previous": "Précédent",
    "next": "Suivant",
    
    // Compte Boutique Chaussures
    "sign_in": "Se connecter",
    "new_customer": "Nouveau client ?",
    "start_here": "Commencez ici",
    "your_account": "Votre compte",
    "your_orders": "Vos commandes",
    "your_wishlist": "Votre liste de souhaits",
    "your_recommendations": "Vos recommandations",
    "your_favorites": "Vos favoris",
    "your_recent_views": "Vos vues récentes",
    "your_size_preferences": "Vos tailles préférées",
    "your_brands_preferences": "Vos marques préférées",
    "your_addresses": "Vos adresses",
    "your_payment_options": "Vos moyens de paiement",
    "your_gift_cards": "Vos cartes cadeaux",
    "your_coupons": "Vos coupons",
    "your_loyalty_points": "Vos points fidélité",
    "your_notifications": "Vos notifications",
    "your_help": "Votre aide",
    "customer_service": "Service client",
    "help": "Aide",
    "contact_us": "Nous contacter",
    "returns_exchanges": "Retours et échanges",
    "shipping_info": "Informations de livraison",
    "size_guide": "Guide des tailles",
    "your_lists": "Vos listes",
    "create_list": "Créer une liste",
    "find_list": "Trouver une liste",
    "your_account_lists": "Votre compte et vos listes",
    
    // Page produit détaillée
    "home": "Accueil",
    "running": "Running",
    "color": "Couleur",
    "size": "Taille",
    "quantity": "Quantité",
    "please_select_size_color": "Veuillez sélectionner une taille et une couleur",
    "add_to_cart": "Ajouter au panier",
    "buy_now": "Acheter maintenant",
    "add_to_wishlist": "Ajouter à la liste de souhaits",
    "share": "Partager",
    "warranty_info": "Garantie 2 ans incluse",
    "free_shipping": "Livraison gratuite",
    "sold_by": "Vendu par",
    "product_description": "Description du produit",
    "key_features": "Caractéristiques principales",
    "technical_specifications": "Spécifications techniques",
    "reviews": "Avis",
    "customer_reviews": "Avis clients",
    "write_review": "Écrire un avis",
    "questions_answers": "Questions et réponses",
    "ask_question": "Poser une question",
    "similar_products": "Produits similaires",
    "view_product": "Voir le produit",
    "frequently_bought_together": "Fréquemment achetés ensemble",
    "add_all_to_cart": "Tout ajouter au panier",
    "cart_preview": "Aperçu du panier",
    "subtotal": "Sous-total",
    "shipping": "Livraison",
    "free": "Gratuit",
    "total": "Total",
    "proceed_to_checkout": "Procéder au paiement",
    "view_cart": "Voir le panier",
    "see_more_products": "Voir plus de produits",
    "discover_full_catalog": "Découvrez notre catalogue complet",
    "explore_1000_products": "Explorez plus de 1000 produits avec nos filtres avancés, trouvez exactement ce que vous cherchez et profitez de nos meilleures offres !",
    "advanced_filters": "Filtres avancés",
    "smart_search": "Recherche intelligente",
    "recommended_products": "Produits recommandés",
    "access_full_catalog": "Accéder au catalogue complet",
    
    // Footer
    "about_us": "À propos de nous",
    "about_description": "Votre boutique de chaussures et accessoires de mode depuis 2020. Qualité, style et service client au cœur de notre mission.",
    "categories": "Catégories",
    "all_products": "Tous les produits",
    "newsletter": "Newsletter",
    "newsletter_description": "Restez informé des dernières tendances et offres exclusives !",
    "email_placeholder": "Votre adresse email",
    "newsletter_success": "Inscription réussie",
    "privacy_protected": "Vos données sont protégées",
    "free_shipping": "Livraison gratuite",
    "free_shipping_desc": "Livraison gratuite dès 50€",
    "secure_payment": "Paiement sécurisé",
    "secure_payment_desc": "Paiement 100% sécurisé",
    "easy_returns": "Retours faciles",
    "easy_returns_desc": "30 jours pour changer d'avis",
    "24_7_support": "Support 24/7",
    "24_7_support_desc": "Assistance disponible 24h/24",
    "company_name": "VenteChaussure",
    "all_rights_reserved": "Tous droits réservés",
    "privacy_policy": "Politique de confidentialité",
    "terms_conditions": "Conditions générales",
    "cookies_policy": "Politique des cookies",
    "faq": "FAQ",
    
    // Marques populaires
    "popular_brands": "Marques populaires",
    "popular_brands_subtitle": "Les meilleures marques pour vos chaussures, pantalons, vestes et accessoires",
    "brand_nike_desc": "Chaussures & Sport",
    "brand_adidas_desc": "Chaussures & Vêtements",
    "brand_puma_desc": "Chaussures & Lifestyle",
    "brand_levis_desc": "Pantalons & Jeans",
    "brand_tommy_desc": "Vestes & Pantalons",
    "brand_calvin_desc": "Vestes & Accessoires",
    "see_collection": "Voir la collection",
    "nike": "Nike",
    "adidas": "Adidas",
    "puma": "Puma",
    "new_balance": "New Balance",
    "converse": "Converse",
    "vans": "Vans",
    
    // Produits populaires
    "popular_products": "Produits populaires",
    "popular_products_subtitle": "Découvrez nos produits les plus vendus et appréciés",
    "best_seller": "Meilleure vente",
    "trending": "Tendance",
    "hot": "Populaire",
    "popular": "Populaire",
    "sold": "vendus",
    "reviews": "avis",
    "view_product": "Voir le produit",
    
    // Pourquoi nous choisir
    "why_choose_us": "Pourquoi nous choisir",
    "why_choose_us_subtitle": "Découvrez ce qui nous rend uniques et pourquoi nos clients nous font confiance",
    "quality_guarantee_title": "Garantie qualité",
    "quality_guarantee_desc": "Tous nos produits sont garantis qualité premium avec des matériaux durables",
    "fast_delivery_title": "Livraison rapide",
    "fast_delivery_desc": "Livraison express en 24-48h partout en France",
    "secure_payment_title": "Paiement sécurisé",
    "easy_returns_title": "Retours faciles",
    "customer_support_title": "Support client",
    "customer_support_desc": "Notre équipe est disponible 24/7 pour vous accompagner",
    "worldwide_shipping_title": "Livraison mondiale",
    "worldwide_shipping_desc": "Livraison dans plus de 50 pays avec suivi en temps réel",
    
    // Statistiques
    "happy_customers": "clients satisfaits",
    "satisfaction_rate": "taux de satisfaction",
    "trusted_by": "Fait confiance par",
    "certified_products": "Produits certifiés",
    "secure_website": "Site sécurisé",
    "award_winning": "Primé",
    "community_trusted": "Approuvé par la communauté",
    "years_experience": "années d'expérience",
    "customer_loved": "Adoré par nos clients",
    "ready_to_shop": "Prêt à faire vos achats ?",
    "ready_to_shop_desc": "Rejoignez des milliers de clients satisfaits et découvrez notre sélection exceptionnelle",
    
    // Témoignages
    "customer_testimonials": "Témoignages clients",
    "testimonials_subtitle": "Ce que disent nos clients satisfaits",
    "Marie Dubois": "Marie Dubois",
    "testimonial_1_text": "J'ai acheté mes Nike Air Max 270 ici et je suis ravie ! La qualité est exceptionnelle et la livraison a été rapide. Je recommande vivement !",
    "Paris, France": "Paris, France",
    "purchased": "a acheté",
    "satisfied_customers": "clients satisfaits",
    "average_rating": "note moyenne",
    
    // Section vidéo
    "discover_our_videos": "Découvrez nos vidéos",
    "video_section_subtitle": "Explorez nos collections en vidéo et découvrez nos produits sous tous les angles",
    "video_collection_title": "Collection vidéo",
    "video_collection_desc": "Découvrez nos dernières collections en vidéo haute qualité",
    "watch_now": "Regarder maintenant",
    "collection": "collection",
    "video_quality_title": "Test qualité",
    "video_quality_desc": "Voyez nos tests de qualité en action",
    "quality": "qualité",
    "video_trends_title": "Tendances mode",
    "video_trends_desc": "Restez à jour avec les dernières tendances",
    "trends": "tendances",
    "featured_video_title": "Vidéo en vedette",
    "featured_video_desc": "Notre vidéo la plus populaire du moment",
    "video_categories": "Catégories vidéo",
    "product_collections": "Collections produits",
    "quality_tests": "Tests qualité",
    "fashion_trends": "Tendances de moda",
    
    // Boutons et actions
    "view_all_popular_products": "Voir tous les produits populaires",
    "start_shopping": "Commencer mes achats",
    "learn_more": "En savoir plus",
    
    // Additional keys for footer
    "language": "Langue",
    "follow_us": "Suivez-nous",
    "quick_links": "Liens rapides",
    "customer_care": "Service client",
    "newsletter_signup": "Inscription newsletter",
    "stay_connected": "Restez connecté",
    "get_in_touch": "Contactez-nous",
    "help_support": "Aide & Support",
    "legal": "Mentions légales",
    "social_media": "Réseaux sociaux",
    // Offres promotionnelles slider
    "flash_sale_title": "Vente flash exceptionnelle !",
    "flash_sale_subtitle": "Profitez de réductions limitées sur une sélection de produits.",
    "new_customer_offer_title": "Offre spéciale nouveaux clients !",
    "new_customer_offer_subtitle": "Bénéficiez de 20€ de réduction sur votre première commande.",
    "free_shipping_offer_title": "Livraison gratuite !",
    "free_shipping_offer_subtitle": "La livraison est offerte sur toutes vos commandes aujourd'hui.",
    "limited_time": "Temps limité",
    "shop_now": "Acheter maintenant",
    "off": "de réduction",
    // Clés pour le timer du slider
    "days": "jours",
    "hours": "heures",
    "minutes": "minutes",
    "seconds": "secondes"
  },
  EN: {
    // Header
    "deliverTo": "Deliver to",
    "searchIn": "Search in",
    "hello": "Hello, sign in",
    "accountLists": "Account & Lists",
    "signIn": "Sign in / Create account",
    "orders": "Your Orders",
    "favourites": "Your Favourites",
    "returns": "Your Returns",
    "addresses": "Your Addresses",
    "payment": "Your Payment Methods",
    "lists": "Your Lists",
    "logout": "Sign out",
    "returnsShort": "Returns",
    "andOrders": "& Orders",
    "cart": "Cart",
    "all": "All",
    "dailyDeals": "Today's Deals",
    "customerService": "Customer Service",
    "giftCards": "Gift Cards",
    "sell": "Sell",
    "close": "Close menu",
    "deliver_to": "Deliver to",
    "hello_identify": "Hello, sign in",
    "account_lists": "Account & Lists",
    "login": "Sign in",
    "create_account": "Create account",
    "and_orders": "& Orders",
    "search_placeholder": "Search in",
    "shoes": "Shoes",
    "clothing": "Clothing",
    "accessories": "Accessories",
    "promotions": "Promotions",
    "new": "New",
    "deals": "Today's Deals",
    "gift_cards": "Gift Cards",
    "pants": "Pants",
    "jackets_coats": "Jackets & Coats",
    "bags": "Bags",
    "belts": "Belts",
    "glasses": "Glasses",
    "ongoing_offers": "Ongoing offers",
    "recent_products": "Recent products",
    // Catégories
    "chaussures": "Shoes",
    "pantalons": "Trousers",
    "vestes": "Jackets",
    "accessoires": "Accessories",
    "Homme": "Men",
    "Femme": "Women",
    "Enfant": "Kids",
    "Bébé": "Baby",
    "Ceintures": "Gürtel",
    "Sacs": "Taschen",
    "Lunettes": "Brillen",
    "Casquettes": "Mützen",
    "Offres en cours": "Aktuelle Angebote",
    "Nouveautés": "Neuheiten",
    "Produits récents": "Neue Produkte",
    "Meilleures ventes": "Bestseller",
    
    // MainContent
    "kitchen_essentials": "Küchen-Essentials",
    "under_50": "Under $50",
    "sneakers_collection": "Sneaker-Kollektion",
    "spring_new_2025": "Spring 2025 New Arrivals",
    "special_offers": "Special Offers",
    "up_to_40_off": "Up to -40% on selection",
    "trendy_shoes_for_all": "Trendy shoes for all",
    "stylish_pants_for_every_occasion": "Stylish pants for every occasion",
    "elegant_jackets_for_all_seasons": "Elegant jackets for all seasons",
    "accessories_that_complete_your_style": "Accessories that complete your style",
    "current_offers_and_new": "Current offers and new arrivals",
    "man": "Men",
    "woman": "Women",
    "child": "Children",
    "baby": "Baby",
    "see_all_offers": "See all offers",
    "nike_air_max_270": "Nike Air Max 270 Shoes",
    "adidas_ultraboost_22": "Adidas Ultraboost 22",
    "puma_rs_x": "Puma RS-X",
    "new_balance_574": "New Balance 574",
    "levis_501_jeans": "Levi's 501 Jeans",
    "calvin_klein_chinos": "Calvin Klein Chinos",
    "tommy_hilfiger_cargo": "Tommy Hilfiger Cargo",
    "gap_slim_fit": "Gap Slim Fit",
    "north_face_jacket": "The North Face Jacket",
    "columbia_omni_heat": "Columbia Omni-Heat",
    "patagonia_down_jacket": "Patagonia Down Jacket",
    "canada_goose_parka": "Canada Goose Parka",
    "louis_vuitton_bag": "Louis Vuitton Bag",
    "gucci_belt": "Gucci Belt",
    "ray_ban_sunglasses": "Ray-Ban Sunglasses",
    "rolex_watch": "Rolex Watch",
    "nike_air_jordan": "Nike Air Jordan",
    "adidas_yeezy": "Adidas Yeezy",
    "supreme_hoodie": "Supreme Hoodie",
    "off_white_sneakers": "Off-White Sneakers",
    
    // Pages catégories
    "welcome_to_man_page": "Welcome to the Men page",
    "welcome_to_woman_page": "Welcome to the Women page",
    "welcome_to_child_page": "Welcome to the Children page",
    "welcome_to_baby_page": "Welcome to the Baby page",
    "man_category_page": "Men category page",
    "woman_category_page": "Women category page",
    "child_category_page": "Children category page",
    "baby_category_page": "Baby category page",
    
    // Page catégorie Homme
    "filters": "Filters",
    "brands": "Brands",
    "price": "Price",
    "all_prices": "All prices",
    "under": "Under",
    "over": "Over",
    "availability": "Availability",
    "in_stock": "In stock",
    "prime": "Prime",
    "results_for": "results for",
    "man_shoes": "men's shoes",
    "sort_by": "Sort by",
    "featured": "Featured",
    "price_low_to_high": "Price: Low to High",
    "price_high_to_low": "Price: High to Low",
    "customer_reviews": "Customer Reviews",
    "newest_arrivals": "Newest Arrivals",
    "fast_delivery": "Fast delivery",
    "out_of_stock": "Out of stock",
    "add_to_cart": "Add to Cart",
    "previous": "Previous",
    "next": "Next",
    
    // Compte Boutique Chaussures
    "sign_in": "Sign in",
    "new_customer": "New customer?",
    "start_here": "Start here",
    "your_account": "Your Account",
    "your_orders": "Your Orders",
    "your_wishlist": "Your Wish List",
    "your_recommendations": "Your Recommendations",
    "your_favorites": "Your Favorites",
    "your_recent_views": "Your Recent Views",
    "your_size_preferences": "Your Size Preferences",
    "your_brands_preferences": "Your Brand Preferences",
    "your_addresses": "Your Addresses",
    "your_payment_options": "Your Payment Options",
    "your_gift_cards": "Your Gift Cards",
    "your_coupons": "Your Coupons",
    "your_loyalty_points": "Your Loyalty Points",
    "your_notifications": "Your Notifications",
    "your_help": "Your Help",
    "customer_service": "Customer Service",
    "help": "Help",
    "contact_us": "Contact Us",
    "returns_exchanges": "Returns & Exchanges",
    "shipping_info": "Shipping Info",
    "size_guide": "Size Guide",
    "your_lists": "Your Lists",
    "create_list": "Create a List",
    "find_list": "Find a List",
    "your_account_lists": "Your Account & Lists",
    
    // Page produit détaillée
    "home": "Home",
    "running": "Running",
    "color": "Color",
    "size": "Size",
    "quantity": "Quantity",
    "please_select_size_color": "Please select a size and color",
    "add_to_cart": "Add to Cart",
    "buy_now": "Buy Now",
    "add_to_wishlist": "Add to Wishlist",
    "share": "Share",
    "warranty_info": "2-year warranty included",
    "free_shipping": "Free shipping",
    "sold_by": "Sold by",
    "product_description": "Product Description",
    "key_features": "Key Features",
    "technical_specifications": "Technical Specifications",
    "reviews": "Reviews",
    "customer_reviews": "Customer Reviews",
    "write_review": "Write a Review",
    "questions_answers": "Questions & Answers",
    "ask_question": "Ask a Question",
    "similar_products": "Similar Products",
    "view_product": "View Product",
    "frequently_bought_together": "Frequently Bought Together",
    "add_all_to_cart": "Add All to Cart",
    "cart_preview": "Cart Preview",
    "subtotal": "Subtotal",
    "shipping": "Shipping",
    "free": "Free",
    "total": "Total",
    "proceed_to_checkout": "Proceed to Checkout",
    "view_cart": "View Cart",
    "see_more_products": "See more products",
    "discover_full_catalog": "Discover our full catalog",
    "explore_1000_products": "Explore over 1000 products with our advanced filters, find exactly what you need and enjoy our best deals!",
    "advanced_filters": "Advanced filters",
    "smart_search": "Smart search",
    "recommended_products": "Recommended products",
    "access_full_catalog": "Access the full catalog",
    
    // Footer
    "about_us": "About Us",
    "about_description": "Your fashion shoes and accessories store since 2020. Quality, style and customer service at the heart of our mission.",
    "categories": "Categories",
    "all_products": "All Products",
    "newsletter": "Newsletter",
    "newsletter_description": "Stay informed of the latest trends and exclusive offers!",
    "email_placeholder": "Your email address",
    "newsletter_success": "Subscription successful",
    "privacy_protected": "Your data is protected",
    "free_shipping": "Free Shipping",
    "free_shipping_desc": "Free shipping from €50",
    "secure_payment": "Secure Payment",
    "secure_payment_desc": "100% secure payment",
    "easy_returns": "Easy Returns",
    "easy_returns_desc": "30 days to change your mind",
    "24_7_support": "24/7 Support",
    "24_7_support_desc": "Assistance available 24/7",
    "company_name": "VenteChaussure",
    "all_rights_reserved": "All rights reserved",
    "privacy_policy": "Privacy Policy",
    "terms_conditions": "Terms & Conditions",
    "cookies_policy": "Cookies Policy",
    "faq": "FAQ",
    
    // Marques populaires
    "popular_brands": "Popular Brands",
    "popular_brands_subtitle": "The best brands for your shoes, pants, jackets and accessories",
    "brand_nike_desc": "Shoes & Sport",
    "brand_adidas_desc": "Shoes & Clothing",
    "brand_puma_desc": "Shoes & Lifestyle",
    "brand_levis_desc": "Pants & Jeans",
    "brand_tommy_desc": "Jackets & Pants",
    "brand_calvin_desc": "Jackets & Accessories",
    "see_collection": "See the collection",
    "nike": "Nike",
    "adidas": "Adidas",
    "puma": "Puma",
    "new_balance": "New Balance",
    "converse": "Converse",
    "vans": "Vans",
    
    // Produits populaires
    "popular_products": "Popular Products",
    "popular_products_subtitle": "Discover our best-selling and most loved products",
    "best_seller": "Best Seller",
    "trending": "Trending",
    "hot": "Hot",
    "popular": "Popular",
    "sold": "sold",
    "reviews": "reviews",
    "view_product": "View Product",
    
    // Why Choose Us
    "why_choose_us": "Why Choose Us",
    "why_choose_us_subtitle": "Discover what makes us unique and why our customers trust us",
    "quality_guarantee_title": "Quality Guarantee",
    "quality_guarantee_desc": "All our products are guaranteed premium quality with durable materials",
    "fast_delivery_title": "Fast Delivery",
    "fast_delivery_desc": "Express delivery in 24-48h throughout France",
    "secure_payment_title": "Secure Payment",
    "easy_returns_title": "Easy Returns",
    "customer_support_title": "Customer Support",
    "customer_support_desc": "Our team is available 24/7 to assist you",
    "worldwide_shipping_title": "Worldwide Shipping",
    "worldwide_shipping_desc": "Shipping to over 50 countries with real-time tracking",
    
    // Statistiques
    "happy_customers": "happy customers",
    "satisfaction_rate": "satisfaction rate",
    "trusted_by": "Trusted by",
    "certified_products": "Certified Products",
    "secure_website": "Secure Website",
    "award_winning": "Award Winning",
    "community_trusted": "Community Trusted",
    "years_experience": "years experience",
    "customer_loved": "Customer Loved",
    "ready_to_shop": "Ready to shop?",
    "ready_to_shop_desc": "Join thousands of satisfied customers and discover our exceptional selection",
    
    // Testimonials
    "customer_testimonials": "Customer Testimonials",
    "testimonials_subtitle": "What our satisfied customers say",
    "Marie Dubois": "Marie Dubois",
    "testimonial_1_text": "I bought my Nike Air Max 270 here and I'm delighted! The quality is exceptional and delivery was fast. I highly recommend!",
    "Paris, France": "Paris, France",
    "purchased": "purchased",
    "satisfied_customers": "satisfied customers",
    "average_rating": "average rating",
    
    // Video Section
    "discover_our_videos": "Discover Our Videos",
    "video_section_subtitle": "Explore our collections in video and discover our products from all angles",
    "video_collection_title": "Video Collection",
    "video_collection_desc": "Discover our latest collections in high quality video",
    "watch_now": "Watch Now",
    "collection": "collection",
    "video_quality_title": "Quality Test",
    "video_quality_desc": "See our quality tests in action",
    "quality": "quality",
    "video_trends_title": "Fashion Trends",
    "video_trends_desc": "Stay up to date with the latest trends",
    "trends": "trends",
    "featured_video_title": "Featured Video",
    "featured_video_desc": "Our most popular video of the moment",
    "video_categories": "Video Categories",
    "product_collections": "Product Collections",
    "quality_tests": "Quality Tests",
    "fashion_trends": "Fashion Trends",
    
    // Boutons et actions
    "view_all_popular_products": "Voir tous les produits populaires",
    "start_shopping": "Commencer mes achats",
    "learn_more": "En savoir plus",
    
    // Additional keys for footer
    "language": "Language",
    "follow_us": "Follow Us",
    "quick_links": "Quick Links",
    "customer_care": "Customer Care",
    "newsletter_signup": "Newsletter Signup",
    "stay_connected": "Stay Connected",
    "get_in_touch": "Get in Touch",
    "help_support": "Help & Support",
    "legal": "Legal",
    "social_media": "Réseaux sociaux",
    // Promotional offers slider (EN)
    "flash_sale_title": "Flash Sale!",
    "flash_sale_subtitle": "Enjoy limited-time discounts on selected products.",
    "new_customer_offer_title": "Special Offer for New Customers!",
    "new_customer_offer_subtitle": "Get €20 off your first order.",
    "free_shipping_offer_title": "Free Shipping!",
    "free_shipping_offer_subtitle": "Free shipping on all your orders today.",
    "limited_time": "Limited time",
    "shop_now": "Shop now",
    "off": "off",
    // Timer keys (EN)
    "days": "days",
    "hours": "hours",
    "minutes": "minutes",
    "seconds": "seconds"
  },
  ES: {
    // Header
    "deliverTo": "Entregar a",
    "searchIn": "Buscar en",
    "hello": "Hola, identifícate",
    "accountLists": "Cuenta y Listas",
    "signIn": "Iniciar sesión / Crear cuenta",
    "orders": "Tus pedidos",
    "favourites": "Tus favoritos",
    "returns": "Tus devoluciones",
    "addresses": "Tus direcciones",
    "payment": "Tus métodos de pago",
    "lists": "Tus listas",
    "logout": "Cerrar sesión",
    "returnsShort": "Devoluciones",
    "andOrders": "y Pedidos",
    "cart": "Cesta",
    "all": "Todas",
    "dailyDeals": "Ofertas del día",
    "customerService": "Atención al cliente",
    "giftCards": "Tarjetas regalo",
    "sell": "Vender",
    "close": "Cerrar menú",
    "deliver_to": "Entregar a",
    "hello_identify": "Hola, identifícate",
    "account_lists": "Cuenta y Listas",
    "login": "Iniciar sesión",
    "create_account": "Crear cuenta",
    "and_orders": "y Pedidos",
    "search_placeholder": "Buscar en",
    "shoes": "Zapatos",
    "clothing": "Ropa",
    "accessories": "Accesorios",
    "promotions": "Promociones",
    "new": "Novedades",
    "deals": "Ofertas del día",
    "gift_cards": "Tarjetas de Regalo",
    "pants": "Pantalones",
    "jackets_coats": "Chaquetas y Abrigos",
    "bags": "Bolsos",
    "belts": "Cinturones",
    "glasses": "Gafas",
    "ongoing_offers": "Ofertas en curso",
    "recent_products": "Productos recientes",
    
    // MainContent
    "kitchen_essentials": "Essentials de cocina",
    "under_50": "Menos de $50",
    "sneakers_collection": "Colección de Zapatillas",
    "spring_new_2025": "Novedades Primavera 2025",
    "special_offers": "Ofertas Especiales",
    "up_to_40_off": "Hasta -40% en selección",
    "trendy_shoes_for_all": "Zapatos de moda para todos",
    "stylish_pants_for_every_occasion": "Pantalones elegantes para cada ocasión",
    "elegant_jackets_for_all_seasons": "Chaquetas elegantes para todas las estaciones",
    "accessories_that_complete_your_style": "Accesorios que completan tu estilo",
    "current_offers_and_new": "Ofertas actuales y novedades",
    "man": "Hombre",
    "woman": "Mujer",
    "child": "Niño",
    "baby": "Bebé",
    "see_all_offers": "Ver todas las ofertas",
    "nike_air_max_270": "Nike Air Max 270",
    "adidas_ultraboost_22": "Adidas Ultraboost 22",
    "puma_rs_x": "Puma RS-X",
    "new_balance_574": "New Balance 574",
    "levis_501_jeans": "Levi's 501 Jeans",
    "calvin_klein_chinos": "Calvin Klein Chinos",
    "tommy_hilfiger_cargo": "Tommy Hilfiger Cargo",
    "gap_slim_fit": "Gap Slim Fit",
    "north_face_jacket": "The North Face Jacket",
    "columbia_omni_heat": "Columbia Omni-Heat",
    "patagonia_down_jacket": "Patagonia Down Jacket",
    "canada_goose_parka": "Canada Goose Parka",
    "louis_vuitton_bag": "Louis Vuitton Bag",
    "gucci_belt": "Gucci Belt",
    "ray_ban_sunglasses": "Ray-Ban Sunglasses",
    "rolex_watch": "Rolex Watch",
    "nike_air_jordan": "Nike Air Jordan",
    "adidas_yeezy": "Adidas Yeezy",
    "supreme_hoodie": "Supreme Hoodie",
    "off_white_sneakers": "Off-White Sneakers",
    
    // Pages catégories
    "welcome_to_man_page": "Bienvenido a la página Hombre",
    "welcome_to_woman_page": "Bienvenido a la página Mujer",
    "welcome_to_child_page": "Bienvenido a la página Niño",
    "welcome_to_baby_page": "Bienvenido a la página Bebé",
    "man_category_page": "Página categoría Hombre",
    "woman_category_page": "Página categoría Mujer",
    "child_category_page": "Página categoría Niño",
    "baby_category_page": "Página categoría Bebé",
    
    // Page catégorie Homme
    "filters": "Filtros",
    "brands": "Marcas",
    "price": "Precio",
    "all_prices": "Todos los precios",
    "under": "Menos de",
    "over": "Más de",
    "availability": "Disponibilidad",
    "in_stock": "En stock",
    "prime": "Prime",
    "results_for": "resultados para",
    "man_shoes": "zapatos de hombre",
    "sort_by": "Ordenar por",
    "featured": "Destacados",
    "price_low_to_high": "Precio: Menor a Mayor",
    "price_high_to_low": "Precio: Mayor a Menor",
    "customer_reviews": "Reseñas de clientes",
    "newest_arrivals": "Novedades",
    "fast_delivery": "Entrega rápida",
    "out_of_stock": "Agotado",
    "add_to_cart": "Añadir al carrito",
    "previous": "Anterior",
    "next": "Siguiente",
    
    // Compte Boutique Chaussures
    "sign_in": "Iniciar sesión",
    "new_customer": "¿Nuevo cliente?",
    "start_here": "Empieza aquí",
    "your_account": "Tu cuenta",
    "your_orders": "Tus pedidos",
    "your_wishlist": "Tu lista de deseos",
    "your_recommendations": "Tus recomendaciones",
    "your_favorites": "Tus favoritos",
    "your_recent_views": "Tus vistas recientes",
    "your_size_preferences": "Tus tallas preferidas",
    "your_brands_preferences": "Tus marcas preferidas",
    "your_addresses": "Tus direcciones",
    "your_payment_options": "Tus opciones de pago",
    "your_gift_cards": "Tus tarjetas de regalo",
    "your_coupons": "Tus cupones",
    "your_loyalty_points": "Tus puntos de fidelidad",
    "your_notifications": "Tus notificaciones",
    "your_help": "Tu ayuda",
    "customer_service": "Servicio al cliente",
    "help": "Ayuda",
    "contact_us": "Contáctanos",
    "returns_exchanges": "Devoluciones y cambios",
    "shipping_info": "Información de envío",
    "size_guide": "Guía de tallas",
    "your_lists": "Tus listas",
    "create_list": "Crear una lista",
    "find_list": "Encontrar una lista",
    "your_account_lists": "Tu cuenta y listas",
    
    // Page produit détaillée
    "home": "Inicio",
    "running": "Running",
    "color": "Color",
    "size": "Talla",
    "quantity": "Cantidad",
    "please_select_size_color": "Por favor selecciona una talla y color",
    "add_to_cart": "Añadir al carrito",
    "buy_now": "Comprar ahora",
    "add_to_wishlist": "Añadir a la lista de deseos",
    "share": "Compartir",
    "warranty_info": "Garantía de 2 años incluida",
    "free_shipping": "Envío gratuito",
    "sold_by": "Vendido por",
    "product_description": "Descripción del producto",
    "key_features": "Características principales",
    "technical_specifications": "Especificaciones técnicas",
    "reviews": "Reseñas",
    "customer_reviews": "Reseñas de clientes",
    "write_review": "Escribir reseña",
    "questions_answers": "Preguntas y respuestas",
    "ask_question": "Hacer una pregunta",
    "similar_products": "Productos similares",
    "view_product": "Ver producto",
    "frequently_bought_together": "Frecuentemente comprados juntos",
    "add_all_to_cart": "Añadir todo al carrito",
    "cart_preview": "Vista previa del carrito",
    "subtotal": "Subtotal",
    "shipping": "Envío",
    "free": "Gratis",
    "total": "Total",
    "proceed_to_checkout": "Proceder al pago",
    "view_cart": "Ver carrito",
    "see_more_products": "Ver más productos",
    "discover_full_catalog": "Descubre nuestro catálogo completo",
    "explore_1000_products": "¡Explora más de 1000 productos con nuestros filtros avanzados, encuentra exactamente lo que buscas y aprovecha nuestras mejores ofertas!",
    "advanced_filters": "Filtros avanzados",
    "smart_search": "Búsqueda inteligente",
    "recommended_products": "Productos recomendados",
    "access_full_catalog": "Acceder al catálogo completo",
    
    // Footer
    "about_us": "Sobre nosotros",
    "about_description": "Tu tienda de zapatos y accesorios de moda desde 2020. Calidad, estilo y servicio al cliente en el corazón de nuestra misión.",
    "categories": "Categorías",
    "all_products": "Todos los productos",
    "newsletter": "Boletín",
    "newsletter_description": "¡Mantente informado de las últimas tendencias y ofertas exclusivas!",
    "email_placeholder": "Tu dirección de email",
    "newsletter_success": "Suscripción exitosa",
    "privacy_protected": "Tus datos están protegidos",
    "free_shipping": "Envío gratuito",
    "free_shipping_desc": "Envío gratuito desde 50€",
    "secure_payment": "Pago seguro",
    "secure_payment_desc": "Pago 100% seguro",
    "easy_returns": "Devoluciones fáciles",
    "easy_returns_desc": "30 días para cambiar de opinión",
    "24_7_support": "Soporte 24/7",
    "24_7_support_desc": "Asistencia disponible 24/7",
    "company_name": "VenteChaussure",
    "all_rights_reserved": "Todos los derechos reservados",
    "privacy_policy": "Política de privacidad",
    "terms_conditions": "Términos y condiciones",
    "cookies_policy": "Política de cookies",
    "faq": "Preguntas frecuentes",
    
    // Marques populaires
    "popular_brands": "Marcas populares",
    "popular_brands_subtitle": "Las mejores marcas para tus zapatos, pantalones, chaquetas y accesorios",
    "brand_nike_desc": "Zapatos y deporte",
    "brand_adidas_desc": "Zapatos y ropa",
    "brand_puma_desc": "Zapatos y estilo de vida",
    "brand_levis_desc": "Pants & Jeans",
    "brand_tommy_desc": "Chaquetas y pantalones",
    "brand_calvin_desc": "Chaquetas y accesorios",
    "see_collection": "Ver la colección",
    "nike": "Nike",
    "adidas": "Adidas",
    "puma": "Puma",
    "new_balance": "New Balance",
    "converse": "Converse",
    "vans": "Vans",
    
    // Produits populaires
    "popular_products": "Productos populares",
    "popular_products_subtitle": "Descubre nuestros productos más vendidos y apreciados",
    "best_seller": "Más vendido",
    "trending": "Tendencia",
    "hot": "Popular",
    "popular": "Popular",
    "sold": "vendidos",
    "reviews": "reseñas",
    "view_product": "Ver producto",
    
    // Por qué elegirnos
    "why_choose_us": "Por qué elegirnos",
    "why_choose_us_subtitle": "Descubre qué nos hace únicos y por qué nuestros clientes confían en nosotros",
    "quality_guarantee_title": "Garantía de calidad",
    "quality_guarantee_desc": "Todos nuestros productos están garantizados de calidad premium con materiales duraderos",
    "fast_delivery_title": "Entrega rápida",
    "fast_delivery_desc": "Entrega express en 24-48h en toda Francia",
    "secure_payment_title": "Pago seguro",
    "easy_returns_title": "Devoluciones fáciles",
    "customer_support_title": "Soporte al cliente",
    "customer_support_desc": "Nuestro equipo está disponible 24/7 para ayudarte",
    "worldwide_shipping_title": "Envío mundial",
    "worldwide_shipping_desc": "Envío a más de 50 países con seguimiento en tiempo real",
    
    // Estadísticas
    "happy_customers": "clientes satisfechos",
    "satisfaction_rate": "tasa de satisfacción",
    "trusted_by": "Confiado por",
    "certified_products": "Productos certificados",
    "secure_website": "Sitio web seguro",
    "award_winning": "Ganador de premios",
    "community_trusted": "Confiado por la comunidad",
    "years_experience": "años de experiencia",
    "customer_loved": "Amado por los clientes",
    "ready_to_shop": "¿Listo para comprar?",
    "ready_to_shop_desc": "Únete a miles de clientes satisfechos y descubre nuestra selección excepcional",
    
    // Testimonios
    "customer_testimonials": "Testimonios de clientes",
    "testimonials_subtitle": "Lo que dicen nuestros clientes satisfechos",
    "Marie Dubois": "Marie Dubois",
    "testimonial_1_text": "¡Compré mis Nike Air Max 270 aquí y estoy encantada! La calidad es excepcional y la entrega fue rápida. ¡Lo recomiendo mucho!",
    "Paris, France": "París, Francia",
    "purchased": "compró",
    "satisfied_customers": "clientes satisfechos",
    "average_rating": "calificación promedio",
    
    // Videosektion
    "discover_our_videos": "Entdecken Sie unsere Videos",
    "video_section_subtitle": "Erkunden Sie unsere Kollektionen im Video und entdecken Sie unsere Produkte aus allen Winkeln",
    "video_collection_title": "Colección de video",
    "video_collection_desc": "Entdecken Sie unsere neuesten Kollektionen in hochwertigem Video",
    "watch_now": "Jetzt ansehen",
    "collection": "Kollektion",
    "video_quality_title": "Test qualité",
    "video_quality_desc": "Ve nuestras pruebas de calidad en acción",
    "quality": "calidad",
    "video_trends_title": "Tendencias de moda",
    "video_trends_desc": "Mantente al día con las últimas tendencias",
    "trends": "tendances",
    "featured_video_title": "Vidéo en vedette",
    "featured_video_desc": "Notre vidéo la plus populaire du moment",
    "video_categories": "Catégories vidéo",
    "product_collections": "Colecciones de productos",
    "quality_tests": "Pruebas de calidad",
    "fashion_trends": "Fashion Trends",
    
    // Boutons et actions
    "view_all_popular_products": "Voir tous les produits populaires",
    "start_shopping": "Commencer mes achats",
    "learn_more": "En savoir plus",
    
    // Additional keys for footer
    "language": "Idioma",
    "follow_us": "Síguenos",
    "quick_links": "Enlaces rápidos",
    "customer_care": "Atención al cliente",
    "newsletter_signup": "Newsletter-Anmeldung",
    "stay_connected": "Mantente conectado",
    "get_in_touch": "Ponte en contacto",
    "help_support": "Ayuda y soporte",
    "legal": "Legal",
    "social_media": "Réseaux sociaux",
    // Ofertas promocionales slider (ES)
    "flash_sale_title": "¡Venta flash!",
    "flash_sale_subtitle": "Aprovecha descuentos por tiempo limitado en productos seleccionados.",
    "new_customer_offer_title": "¡Oferta especial para nuevos clientes!",
    "new_customer_offer_subtitle": "Obtén 20€ de descuento en tu primer pedido.",
    "free_shipping_offer_title": "¡Envío gratis!",
    "free_shipping_offer_subtitle": "Envío gratis en todos tus pedidos hoy.",
    "limited_time": "Tiempo limitado",
    "shop_now": "Comprar ahora",
    "off": "de descuento",
    // Claves para el temporizador (ES)
    "days": "días",
    "hours": "horas",
    "minutes": "minutos",
    "seconds": "segundos"
  },
  DE: {
    // Header
    "deliverTo": "Liefern an",
    "searchIn": "Suchen in",
    "hello": "Hallo, anmelden",
    "accountLists": "Konto & Listen",
    "signIn": "Anmelden / Konto erstellen",
    "orders": "Ihre Bestellungen",
    "favourites": "Ihre Favoriten",
    "returns": "Ihre Rücksendungen",
    "addresses": "Ihre Adressen",
    "payment": "Ihre Zahlungsmethoden",
    "lists": "Ihre Listen",
    "logout": "Abmelden",
    "returnsShort": "Rücksendungen",
    "andOrders": "und Bestellungen",
    "cart": "Warenkorb",
    "all": "Alle",
    "dailyDeals": "Angebote des Tages",
    "customerService": "Kundenservice",
    "giftCards": "Geschenkkarten",
    "sell": "Verkaufen",
    "close": "Menü schließen",
    "deliver_to": "Liefern an",
    "hello_identify": "Hallo, anmelden",
    "account_lists": "Konto & Listen",
    "login": "Anmelden",
    "create_account": "Konto erstellen",
    "and_orders": "& Bestellungen",
    "search_placeholder": "Suchen in",
    "shoes": "Schuhe",
    "clothing": "Kleidung",
    "accessories": "Accessoires",
    "promotions": "Aktionen",
    "new": "Neu",
    "deals": "Tagesangebote",
    "gift_cards": "Geschenkkarten",
    "pants": "Hosen",
    "jackets_coats": "Jacken & Mäntel",
    "bags": "Taschen",
    "belts": "Gürtel",
    "glasses": "Brillen",
    "ongoing_offers": "Laufende Angebote",
    "recent_products": "Neue Produkte",
    // Catégories
    "chaussures": "Schuhe",
    "pantalons": "Hosen",
    "vestes": "Jacken",
    "accessoires": "Accessoires",
    "Homme": "Herren",
    "Femme": "Damen",
    "Enfant": "Kinder",
    "Bébé": "Baby",
    "Ceintures": "Gürtel",
    "Sacs": "Taschen",
    "Lunettes": "Brillen",
    "Casquettes": "Mützen",
    "Offres en cours": "Aktuelle Angebote",
    "Nouveautés": "Neuheiten",
    "Produits récents": "Neue Produkte",
    "Meilleures ventes": "Bestseller",
    
    // MainContent
    "kitchen_essentials": "Küchen-Essentials",
    "under_50": "Unter $50",
    "sneakers_collection": "Sneaker-Kollektion",
    "spring_new_2025": "Frühling 2025 Neuheiten",
    "special_offers": "Sonderangebote",
    "up_to_40_off": "Bis zu -40% auf Auswahl",
    "trendy_shoes_for_all": "Trendige Schuhe für alle",
    "stylish_pants_for_every_occasion": "Stilvolle Hosen für jeden Anlass",
    "elegant_jackets_for_all_seasons": "Elegant jackets for all seasons",
    "accessories_that_complete_your_style": "Accessories that complete your style",
    "current_offers_and_new": "Aktuelle Angebote und Neuheiten",
    "man": "Mann",
    "woman": "Frau",
    "child": "Kind",
    "baby": "Baby",
    "see_all_offers": "Alle Angebote anzeigen",
    "nike_air_max_270": "Nike Air Max 270",
    "adidas_ultraboost_22": "Adidas Ultraboost 22",
    "puma_rs_x": "Puma RS-X",
    "new_balance_574": "New Balance 574",
    "levis_501_jeans": "Levi's 501 Jeans",
    "calvin_klein_chinos": "Calvin Klein Chinos",
    "tommy_hilfiger_cargo": "Tommy Hilfiger Cargo",
    "gap_slim_fit": "Gap Slim Fit",
    "north_face_jacket": "The North Face Jacket",
    "columbia_omni_heat": "Columbia Omni-Heat",
    "patagonia_down_jacket": "Patagonia Down Jacket",
    "canada_goose_parka": "Canada Goose Parka",
    "louis_vuitton_bag": "Louis Vuitton Bag",
    "gucci_belt": "Gucci Belt",
    "ray_ban_sunglasses": "Ray-Ban Sunglasses",
    "rolex_watch": "Rolex Watch",
    "nike_air_jordan": "Nike Air Jordan",
    "adidas_yeezy": "Adidas Yeezy",
    "supreme_hoodie": "Supreme Hoodie",
    "off_white_sneakers": "Off-White Sneakers",
    
    // Pages catégories
    "welcome_to_man_page": "Willkommen auf der Männer-Seite",
    "welcome_to_woman_page": "Willkommen auf der Frauen-Seite",
    "welcome_to_child_page": "Willkommen auf der Kinder-Seite",
    "welcome_to_baby_page": "Willkommen auf der Baby-Seite",
    "man_category_page": "Männer-Kategorie-Seite",
    "woman_category_page": "Frauen-Kategorie-Seite",
    "child_category_page": "Kinder-Kategorie-Seite",
    "baby_category_page": "Baby-Kategorie-Seite",
    
    // Page catégorie Homme
    "filters": "Filter",
    "brands": "Marken",
    "price": "Preis",
    "all_prices": "Alle Preise",
    "under": "Unter",
    "over": "Über",
    "availability": "Verfügbarkeit",
    "in_stock": "Auf Lager",
    "prime": "Prime",
    "results_for": "Ergebnisse für",
    "man_shoes": "Herrenschuhe",
    "sort_by": "Sortieren nach",
    "featured": "Empfohlen",
    "price_low_to_high": "Preis: Niedrig zu Hoch",
    "price_high_to_low": "Preis: Hoch zu Niedrig",
    "customer_reviews": "Kundenbewertungen",
    "newest_arrivals": "Neueste Ankünfte",
    "fast_delivery": "Schnelle Lieferung",
    "out_of_stock": "Nicht auf Lager",
    "add_to_cart": "In den Warenkorb",
    "previous": "Zurück",
    "next": "Weiter",
    
    // Compte Boutique Chaussures
    "sign_in": "Anmelden",
    "new_customer": "Neuer Kunde?",
    "start_here": "Hier starten",
    "your_account": "Ihr Konto",
    "your_orders": "Ihre Bestellungen",
    "your_wishlist": "Ihre Wunschliste",
    "your_recommendations": "Ihre Empfehlungen",
    "your_favorites": "Ihre Favoriten",
    "your_recent_views": "Ihre letzten Ansichten",
    "your_size_preferences": "Ihre Größenpräferenzen",
    "your_brands_preferences": "Ihre Markenpräferenzen",
    "your_addresses": "Ihre Adressen",
    "your_payment_options": "Ihre Zahlungsoptionen",
    "your_gift_cards": "Ihre Geschenkkarten",
    "your_coupons": "Ihre Gutscheine",
    "your_loyalty_points": "Ihre Treuepunkte",
    "your_notifications": "Ihre Benachrichtigungen",
    "your_help": "Ihre Hilfe",
    "customer_service": "Kundenservice",
    "help": "Hilfe",
    "contact_us": "Kontaktieren Sie uns",
    "returns_exchanges": "Rücksendungen & Umtausch",
    "shipping_info": "Versandinfo",
    "size_guide": "Größenführer",
    "your_lists": "Ihre Listen",
    "create_list": "Liste erstellen",
    "find_list": "Liste finden",
    "your_account_lists": "Ihr Konto & Listen",
    
    // Page produit détaillée
    "home": "Startseite",
    "running": "Laufen",
    "color": "Farbe",
    "size": "Größe",
    "quantity": "Menge",
    "please_select_size_color": "Bitte wählen Sie eine Größe und Farbe",
    "add_to_cart": "In den Warenkorb",
    "buy_now": "Jetzt kaufen",
    "add_to_wishlist": "Zur Wunschliste hinzufügen",
    "share": "Teilen",
    "warranty_info": "2 Jahre Garantie inklusive",
    "free_shipping": "Kostenloser Versand",
    "sold_by": "Verkauft von",
    "product_description": "Produktbeschreibung",
    "key_features": "Hauptmerkmale",
    "technical_specifications": "Technische Spezifikationen",
    "reviews": "Bewertungen",
    "customer_reviews": "Kundenbewertungen",
    "write_review": "Bewertung schreiben",
    "questions_answers": "Fragen & Antworten",
    "ask_question": "Frage stellen",
    "similar_products": "Ähnliche Produkte",
    "view_product": "Produkt anzeigen",
    "frequently_bought_together": "Häufig zusammen gekauft",
    "add_all_to_cart": "Alle in den Warenkorb",
    "cart_preview": "Warenkorb-Vorschau",
    "subtotal": "Zwischensumme",
    "shipping": "Versand",
    "free": "Kostenlos",
    "total": "Gesamt",
    "proceed_to_checkout": "Zur Kasse",
    "view_cart": "Warenkorb anzeigen",
    "see_more_products": "Mehr Produkte anzeigen",
    "discover_full_catalog": "Entdecken Sie unseren vollständigen Katalog",
    "explore_1000_products": "Entdecken Sie über 1000 Produkte mit unseren erweiterten Filtern, finden Sie genau das, was Sie suchen, und profitieren Sie von unseren besten Angeboten!",
    "advanced_filters": "Erweiterte Filter",
    "smart_search": "Intelligente Suche",
    "recommended_products": "Empfohlene Produkte",
    "access_full_catalog": "Zum vollständigen Katalog",
    
    // Footer
    "about_us": "Über uns",
    "about_description": "Ihr Mode-Schuh- und Accessoires-Geschäft seit 2020. Qualität, Stil und Kundenservice im Mittelpunkt unserer Mission.",
    "categories": "Kategorien",
    "all_products": "Alle Produkte",
    "newsletter": "Newsletter",
    "newsletter_description": "Bleiben Sie über die neuesten Trends und exklusive Angebote informiert!",
    "email_placeholder": "Ihre E-Mail-Adresse",
    "newsletter_success": "Anmeldung erfolgreich",
    "privacy_protected": "Ihre Daten sind geschützt",
    "free_shipping": "Kostenloser Versand",
    "free_shipping_desc": "Kostenloser Versand ab 50€",
    "secure_payment": "Sichere Zahlung",
    "secure_payment_desc": "100% sichere Zahlung",
    "easy_returns": "Einfache Rückgabe",
    "easy_returns_desc": "30 Tage zum Überdenken",
    "24_7_support": "24/7 Support",
    "24_7_support_desc": "Assistenz 24/7 verfügbar",
    "company_name": "VenteChaussure",
    "all_rights_reserved": "Alle Rechte vorbehalten",
    "privacy_policy": "Datenschutzrichtlinie",
    "terms_conditions": "Allgemeine Geschäftsbedingungen",
    "cookies_policy": "Cookie-Richtlinie",
    "faq": "FAQ",
    
    // Marques populaires
    "popular_brands": "Beliebte Marken",
    "popular_brands_subtitle": "Die besten Marken für Ihre Schuhe, Hosen, Jacken und Accessoires",
    "brand_nike_desc": "Schuhe & Sport",
    "brand_adidas_desc": "Schuhe & Kleidung",
    "brand_puma_desc": "Schuhe & Lifestyle",
    "brand_levis_desc": "Hosen & Jeans",
    "brand_tommy_desc": "Jacken & Hosen",
    "brand_calvin_desc": "Jacken & Accessoires",
    "see_collection": "Kollektion ansehen",
    "nike": "Nike",
    "adidas": "Adidas",
    "puma": "Puma",
    "new_balance": "New Balance",
    "converse": "Converse",
    "vans": "Vans",
    
    // Produits populaires
    "popular_products": "Beliebte Produkte",
    "popular_products_subtitle": "Entdecken Sie unsere meistverkauften und beliebtesten Produkte",
    "best_seller": "Bestseller",
    "trending": "Trend",
    "hot": "Heiß",
    "popular": "Beliebt",
    "sold": "verkauft",
    "reviews": "Bewertungen",
    "view_product": "Produkt anzeigen",
    
    // Warum uns wählen
    "why_choose_us": "Warum uns wählen",
    "why_choose_us_subtitle": "Entdecken Sie, was uns einzigartig macht und warum unsere Kunden uns vertrauen",
    "quality_guarantee_title": "Garantía de calidad",
    "quality_guarantee_desc": "Todos nuestros productos están garantizados de calidad premium con materiales duraderos",
    "fast_delivery_title": "Entrega rápida",
    "fast_delivery_desc": "Entrega express en 24-48h en toda Francia",
    "secure_payment_title": "Pago seguro",
    "easy_returns_title": "Devoluciones fáciles",
    "customer_support_title": "Soporte al cliente",
    "customer_support_desc": "Nuestro equipo está disponible 24/7 para ayudarte",
    "worldwide_shipping_title": "Envío mundial",
    "worldwide_shipping_desc": "Envío a más de 50 países con seguimiento en tiempo real",
    
    // Statistiken
    "happy_customers": "zufriedene Kunden",
    "satisfaction_rate": "tasa de satisfacción",
    "trusted_by": "Confiado por",
    "certified_products": "Productos certificados",
    "secure_website": "Sitio web seguro",
    "award_winning": "Ganador de premios",
    "community_trusted": "Confiado por la comunidad",
    "years_experience": "años de experiencia",
    "customer_loved": "Von Kunden geliebt",
    "ready_to_shop": "Bereit zum Einkaufen?",
    "ready_to_shop_desc": "Únete a miles de clientes satisfechos y descubre nuestra selección excepcional",
    
    // Testimonios
    "customer_testimonials": "Kundenbewertungen",
    "testimonials_subtitle": "Was unsere zufriedenen Kunden sagen",
    "Marie Dubois": "Marie Dubois",
    "testimonial_1_text": "¡Compré mis Nike Air Max 270 aquí y estoy encantada! La calidad es excepcional y la entrega fue rápida. ¡Lo recomiendo mucho!",
    "Paris, France": "Paris, Frankreich",
    "purchased": "gekauft",
    "satisfied_customers": "zufriedene Kunden",
    "average_rating": "durchschnittliche Bewertung",
    
    // Videosektion
    "discover_our_videos": "Entdecken Sie unsere Videos",
    "video_section_subtitle": "Erkunden Sie unsere Kollektionen im Video und entdecken Sie unsere Produkte aus allen Winkeln",
    "video_collection_title": "Colección de video",
    "video_collection_desc": "Entdecken Sie unsere neuesten Kollektionen in hochwertigem Video",
    "watch_now": "Jetzt ansehen",
    "collection": "Kollektion",
    "video_quality_title": "Test qualité",
    "video_quality_desc": "Ve nuestras pruebas de calidad en acción",
    "quality": "calidad",
    "video_trends_title": "Tendencias de moda",
    "video_trends_desc": "Mantente al día con las últimas tendencias",
    "trends": "tendances",
    "featured_video_title": "Vidéo en vedette",
    "featured_video_desc": "Notre vidéo la plus populaire du moment",
    "video_categories": "Catégories vidéo",
    "product_collections": "Colecciones de productos",
    "quality_tests": "Pruebas de calidad",
    "fashion_trends": "Fashion Trends",
    
    // Boutons et actions
    "view_all_popular_products": "Voir tous les produits populaires",
    "start_shopping": "Commencer mes achats",
    "learn_more": "En savoir plus",
    
    // Additional keys for footer
    "language": "Sprache",
    "follow_us": "Folgen Sie uns",
    "quick_links": "Schnelllinks",
    "customer_care": "Kundenservice",
    "newsletter_signup": "Newsletter-Anmeldung",
    "stay_connected": "Bleiben Sie verbunden",
    "get_in_touch": "Kontakt aufnehmen",
    "help_support": "Aide & Support",
    "legal": "Mentions légales",
    "social_media": "Réseaux sociaux",
    // Slider-Angebote (DE)
    "flash_sale_title": "Blitzverkauf!",
    "flash_sale_subtitle": "Genießen Sie zeitlich begrenzte Rabatte auf ausgewählte Produkte.",
    "new_customer_offer_title": "Sonderangebot für Neukunden!",
    "new_customer_offer_subtitle": "Erhalten Sie 20€ Rabatt auf Ihre erste Bestellung.",
    "free_shipping_offer_title": "Kostenloser Versand!",
    "free_shipping_offer_subtitle": "Kostenloser Versand auf alle Ihre Bestellungen heute.",
    "limited_time": "Begrenzte Zeit",
    "shop_now": "Jetzt kaufen",
    "off": "Rabatt",
    // Timer-Schlüssel (DE)
    "days": "Tage",
    "hours": "Stunden",
    "minutes": "Minuten",
    "seconds": "Sekunden"
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState("FR");

  const changeLanguage = (languageCode) => {
    setCurrentLanguage(languageCode);
    console.log(`Langue changée : ${languages.find(lang => lang.code === languageCode)?.name}`);
  };

  const t = (key) => {
    return translations[currentLanguage]?.[key] || key;
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    languages
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}; 